Jahia/external-provider-users-groups

core/pom.xml, pom.xml, test/pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-11952 : Update version

core/pom.xml, test/pom.xml
https://jira.jahia.org/browse/BACKLOG-11952
Update dependencies
=> BACKLOG-11952: Update dependencies

core/pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-11952: Make imports mandatory

core/src/javascript/registrations/externalProvider/registerRoutes.js, core/yarn.lock
https://jira.jahia.org/browse/BACKLOG-11710
Add requiredPermission into routes
=> BACKLOG-11710: Add requiredPermission into routes

core/package.json
https://jira.jahia.org/browse/BACKLOG-12722
Update registration
=> BACKLOG-12722 Update package.json

core/src/javascript/registrations/externalProvider/registerRoutes.js
https://jira.jahia.org/browse/PROJECT-XXX
=> BACKLOG-12820: Adapted adminRoute format

core/src/javascript/registrations/externalProvider/registerRoutes.js
https://jira.jahia.org/browse/BACKLOG-12935
Simple reordering of the server administration panels
=> BACKLOG-12935: reordering of the server settings

core/src/main/resources/javascript/locales/de.json, core/src/main/resources/javascript/locales/en.json, core/src/main/resources/javascript/locales/fr.json
https://jira.jahia.org/browse/BACKLOG-12936
Fixed label for user and group providers in admin
=> BACKLOG-12936: Fixed labels in server settings

LICENSE.txt, core/pom.xml, core/src/main/java/org/jahia/modules/external/users/BaseUserGroupProvider.java, core/src/main/java/org/jahia/modules/external/users/ExternalUserGroupService.java, core/src/main/java/org/jahia/modules/external/users/ExternalUserGroupServiceListener.java, core/src/main/java/org/jahia/modules/external/users/GroupNotFoundException.java, core/src/main/java/org/jahia/modules/external/users/JCRExternalUserNode.java, core/src/main/java/org/jahia/modules/external/users/Member.java, core/src/main/java/org/jahia/modules/external/users/UserGroupProvider.java, core/src/main/java/org/jahia/modules/external/users/UserGroupProviderConfiguration.java, core/src/main/java/org/jahia/modules/external/users/UserGroupProviderRegistration.java, core/src/main/java/org/jahia/modules/external/users/UserNotFoundException.java, core/src/main/java/org/jahia/modules/external/users/admin/UserGroupProviderAdminFlow.java, core/src/main/java/org/jahia/modules/external/users/admin/UserGroupProviderInfo.java, core/src/main/java/org/jahia/modules/external/users/impl/ExternalUserGroupServiceImpl.java, core/src/main/java/org/jahia/modules/external/users/impl/GroupDataSource.java, core/src/main/java/org/jahia/modules/external/users/impl/SearchCriteriaHelper.java, core/src/main/java/org/jahia/modules/external/users/impl/UserDataSource.java, core/src/main/java/org/jahia/modules/external/users/rules/ExternalUserGroupRuleService.java, core/src/main/resources/META-INF/LICENSE.txt, pom.xml, test/pom.xml, test/src/main/java/org/jahia/test/external/users/ExternalUsersProviderTest.java, test/src/main/java/org/jahia/test/external/users/TxtxUserGroupProvider.java, test/src/main/resources/META-INF/LICENSE.txt
=> Updated Copyright year

core/pom.xml, test/pom.xml
https://jira.jahia.org/browse/BACKLOG-13160
=> BACKLOG-13160 : Add spring requirement

core/pom.xml
https://jira.jahia.org/browse/PROJECT-XXX
=> Update app-shell dependency

pom.xml
https://jira.jahia.org/browse/QA-13595 
Update parent version
=> QA-13595 Update parent version

core/package.json, core/pom.xml, core/webpack.config.js, core/yarn.lock
https://jira.jahia.org/browse/BACKLOG-15990
=> BACKLOG-15990: Fix JS package vulnerabilities

core/pom.xml, core/src/main/import/repository.xml
https://jira.jahia.org/browse/TECH-1086
=> TECH-1086: Update dependencies

.gitignore, core/package.json, core/pom.xml, core/yarn.lock
https://jira.jahia.org/browse/TECH-1252
=> TECH-1252: Add sync-pom configuration

.github/workflows/on-merge.yml, .github/workflows/on-release.yml, core/package.json, core/pom.xml, core/webpack.config.js, core/yarn.lock
https://jira.jahia.org/browse/TECH-1265
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release
=> TECH-1265: Add SBOM creation

core/package.json
https://jira.jahia.org/browse/TECH-1288
=> TECH-1288: Fixed package name

.github/workflows/on-code-change.yml, .github/workflows/schedule-sonar.yml, core/package.json, core/pom.xml, core/yarn.lock
https://jira.jahia.org/browse/TECH-1662
Upgrade cyclonedx plugins for SBOM creation (mainly to get the project built and added to production Dependency Track).
=> TECH-1662: Upgrade cyclonedx plugins for SBOM creation

test/src/main/java/org/jahia/test/external/users/ExternalUsersProviderTest.java, test/src/main/java/org/jahia/test/external/users/TxtxUserGroupProvider.java
https://jira.jahia.org/browse/TECH-1416
Remove guava usage prior to Java SDK 
=> TECH-1416: Remove guava dependency from test-module

.github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-23385
=> BACKLOG-23385: Add slack notification

.github/workflows/on-release.yml
https://jira.jahia.org/browse/BACKLOG-23385
=> BACKLOG-23385: Add workaround in release wf

.github/maven.settings.xml
https://jira.jahia.org/browse/BACKLOG-23385
=> BACKLOG-23385: Add missing Maven profiles
